// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, useMutation, type UseMutationOptions, useQuery } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createIssue, deleteAttachment, deleteIssue, downloadAttachment, getIssue, listIssues, type Options, searchUsers, updateIssue, uploadAttachment, validateIssueTitle } from '../sdk.gen';
import type { CreateIssueData, CreateIssueError, CreateIssueResponse, DeleteAttachmentData, DeleteAttachmentError, DeleteAttachmentResponse, DeleteIssueData, DeleteIssueError, DeleteIssueResponse, DownloadAttachmentData, DownloadAttachmentError, DownloadAttachmentResponse, GetIssueData, GetIssueError, GetIssueResponse, ListIssuesData, ListIssuesError, ListIssuesResponse, SearchUsersData, SearchUsersError, SearchUsersResponse, UpdateIssueData, UpdateIssueError, UpdateIssueResponse, UploadAttachmentData, UploadAttachmentError, UploadAttachmentResponse, ValidateIssueTitleData, ValidateIssueTitleError, ValidateIssueTitleResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listIssuesQueryKey = (options?: Options<ListIssuesData>) => createQueryKey('listIssues', options, false, ['issues']);

/**
 * List all issues
 */
const listIssuesOptions = (options?: Options<ListIssuesData>) => queryOptions<ListIssuesResponse, ListIssuesError, ListIssuesResponse, ReturnType<typeof listIssuesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listIssues({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listIssuesQueryKey(options)
});

/**
 * List all issues
 */
export const useListIssuesQuery = (options?: Options<ListIssuesData>) => useQuery(listIssuesOptions(options));

/**
 * Create an issue
 */
export const createIssueMutation = (options?: Partial<Options<CreateIssueData>>): UseMutationOptions<CreateIssueResponse, CreateIssueError, Options<CreateIssueData>> => {
    const mutationOptions: UseMutationOptions<CreateIssueResponse, CreateIssueError, Options<CreateIssueData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createIssue({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create an issue
 */
export const useCreateIssueMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<CreateIssueResponse, CreateIssueError, Options<CreateIssueData>>, 'mutationFn'>>) => useMutation({ ...createIssueMutation(), ...mutationOptions });

/**
 * Delete an issue
 */
export const deleteIssueMutation = (options?: Partial<Options<DeleteIssueData>>): UseMutationOptions<DeleteIssueResponse, DeleteIssueError, Options<DeleteIssueData>> => {
    const mutationOptions: UseMutationOptions<DeleteIssueResponse, DeleteIssueError, Options<DeleteIssueData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteIssue({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete an issue
 */
export const useDeleteIssueMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<DeleteIssueResponse, DeleteIssueError, Options<DeleteIssueData>>, 'mutationFn'>>) => useMutation({ ...deleteIssueMutation(), ...mutationOptions });

export const getIssueQueryKey = (options: Options<GetIssueData>) => createQueryKey('getIssue', options, false, ['issues']);

/**
 * Get an issue by ID
 */
const getIssueOptions = (options: Options<GetIssueData>) => queryOptions<GetIssueResponse, GetIssueError, GetIssueResponse, ReturnType<typeof getIssueQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIssue({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIssueQueryKey(options)
});

/**
 * Get an issue by ID
 */
export const useGetIssueQuery = (options: Options<GetIssueData>) => useQuery(getIssueOptions(options));

/**
 * Update an issue
 */
export const updateIssueMutation = (options?: Partial<Options<UpdateIssueData>>): UseMutationOptions<UpdateIssueResponse, UpdateIssueError, Options<UpdateIssueData>> => {
    const mutationOptions: UseMutationOptions<UpdateIssueResponse, UpdateIssueError, Options<UpdateIssueData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateIssue({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update an issue
 */
export const useUpdateIssueMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<UpdateIssueResponse, UpdateIssueError, Options<UpdateIssueData>>, 'mutationFn'>>) => useMutation({ ...updateIssueMutation(), ...mutationOptions });

export const validateIssueTitleQueryKey = (options: Options<ValidateIssueTitleData>) => createQueryKey('validateIssueTitle', options, false, ['issues']);

/**
 * Check if an issue title is unique
 *
 * Returns whether the given title is available (not yet used by another issue). Useful for async form validation.
 */
const validateIssueTitleOptions = (options: Options<ValidateIssueTitleData>) => queryOptions<ValidateIssueTitleResponse, ValidateIssueTitleError, ValidateIssueTitleResponse, ReturnType<typeof validateIssueTitleQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await validateIssueTitle({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: validateIssueTitleQueryKey(options)
});

/**
 * Check if an issue title is unique
 *
 * Returns whether the given title is available (not yet used by another issue). Useful for async form validation.
 */
export const useValidateIssueTitleQuery = (options: Options<ValidateIssueTitleData>) => useQuery(validateIssueTitleOptions(options));

/**
 * Upload an attachment to an issue
 */
export const uploadAttachmentMutation = (options?: Partial<Options<UploadAttachmentData>>): UseMutationOptions<UploadAttachmentResponse, UploadAttachmentError, Options<UploadAttachmentData>> => {
    const mutationOptions: UseMutationOptions<UploadAttachmentResponse, UploadAttachmentError, Options<UploadAttachmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadAttachment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Upload an attachment to an issue
 */
export const useUploadAttachmentMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<UploadAttachmentResponse, UploadAttachmentError, Options<UploadAttachmentData>>, 'mutationFn'>>) => useMutation({ ...uploadAttachmentMutation(), ...mutationOptions });

/**
 * Delete an attachment
 */
export const deleteAttachmentMutation = (options?: Partial<Options<DeleteAttachmentData>>): UseMutationOptions<DeleteAttachmentResponse, DeleteAttachmentError, Options<DeleteAttachmentData>> => {
    const mutationOptions: UseMutationOptions<DeleteAttachmentResponse, DeleteAttachmentError, Options<DeleteAttachmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAttachment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete an attachment
 */
export const useDeleteAttachmentMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<DeleteAttachmentResponse, DeleteAttachmentError, Options<DeleteAttachmentData>>, 'mutationFn'>>) => useMutation({ ...deleteAttachmentMutation(), ...mutationOptions });

export const downloadAttachmentQueryKey = (options: Options<DownloadAttachmentData>) => createQueryKey('downloadAttachment', options, false, ['Attachments']);

/**
 * Download an attachment
 */
const downloadAttachmentOptions = (options: Options<DownloadAttachmentData>) => queryOptions<DownloadAttachmentResponse, DownloadAttachmentError, DownloadAttachmentResponse, ReturnType<typeof downloadAttachmentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await downloadAttachment({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: downloadAttachmentQueryKey(options)
});

/**
 * Download an attachment
 */
export const useDownloadAttachmentQuery = (options: Options<DownloadAttachmentData>) => useQuery(downloadAttachmentOptions(options));

export const searchUsersQueryKey = (options?: Options<SearchUsersData>) => createQueryKey('searchUsers', options, false, ['Users']);

/**
 * Search users by name
 *
 * Returns matching users for autocomplete. Pass an empty query to list all users.
 */
const searchUsersOptions = (options?: Options<SearchUsersData>) => queryOptions<SearchUsersResponse, SearchUsersError, SearchUsersResponse, ReturnType<typeof searchUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchUsersQueryKey(options)
});

/**
 * Search users by name
 *
 * Returns matching users for autocomplete. Pass an empty query to list all users.
 */
export const useSearchUsersQuery = (options?: Options<SearchUsersData>) => useQuery(searchUsersOptions(options));
