// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateIssueData, CreateIssueErrors, CreateIssueResponses, DeleteAttachmentData, DeleteAttachmentErrors, DeleteAttachmentResponses, DeleteIssueData, DeleteIssueErrors, DeleteIssueResponses, DownloadAttachmentData, DownloadAttachmentErrors, DownloadAttachmentResponses, GetIssueData, GetIssueErrors, GetIssueResponses, ListIssuesData, ListIssuesErrors, ListIssuesResponses, SearchUsersData, SearchUsersErrors, SearchUsersResponses, UpdateIssueData, UpdateIssueErrors, UpdateIssueResponses, UploadAttachmentData, UploadAttachmentErrors, UploadAttachmentResponses, ValidateIssueTitleData, ValidateIssueTitleErrors, ValidateIssueTitleResponses } from './types.gen';
import { zCreateIssueData, zDeleteAttachmentData, zDeleteIssueData, zDownloadAttachmentData, zGetIssueData, zListIssuesData, zSearchUsersData, zUpdateIssueData, zUploadAttachmentData, zValidateIssueTitleData } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all issues
 */
export const listIssues = <ThrowOnError extends boolean = false>(options?: Options<ListIssuesData, ThrowOnError>) => (options?.client ?? client).get<ListIssuesResponses, ListIssuesErrors, ThrowOnError>({
    requestValidator: async (data) => await zListIssuesData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/issues',
    ...options
});

/**
 * Create an issue
 */
export const createIssue = <ThrowOnError extends boolean = false>(options?: Options<CreateIssueData, ThrowOnError>) => (options?.client ?? client).post<CreateIssueResponses, CreateIssueErrors, ThrowOnError>({
    requestValidator: async (data) => await zCreateIssueData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/issues',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete an issue
 */
export const deleteIssue = <ThrowOnError extends boolean = false>(options: Options<DeleteIssueData, ThrowOnError>) => (options.client ?? client).delete<DeleteIssueResponses, DeleteIssueErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeleteIssueData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/issues/{id}',
    ...options
});

/**
 * Get an issue by ID
 */
export const getIssue = <ThrowOnError extends boolean = false>(options: Options<GetIssueData, ThrowOnError>) => (options.client ?? client).get<GetIssueResponses, GetIssueErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetIssueData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/issues/{id}',
    ...options
});

/**
 * Update an issue
 */
export const updateIssue = <ThrowOnError extends boolean = false>(options: Options<UpdateIssueData, ThrowOnError>) => (options.client ?? client).put<UpdateIssueResponses, UpdateIssueErrors, ThrowOnError>({
    requestValidator: async (data) => await zUpdateIssueData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/issues/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Check if an issue title is unique
 *
 * Returns whether the given title is available (not yet used by another issue). Useful for async form validation.
 */
export const validateIssueTitle = <ThrowOnError extends boolean = false>(options: Options<ValidateIssueTitleData, ThrowOnError>) => (options.client ?? client).get<ValidateIssueTitleResponses, ValidateIssueTitleErrors, ThrowOnError>({
    requestValidator: async (data) => await zValidateIssueTitleData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/issues/validate/title',
    ...options
});

/**
 * Upload an attachment to an issue
 */
export const uploadAttachment = <ThrowOnError extends boolean = false>(options: Options<UploadAttachmentData, ThrowOnError>) => (options.client ?? client).post<UploadAttachmentResponses, UploadAttachmentErrors, ThrowOnError>({
    ...formDataBodySerializer,
    requestValidator: async (data) => await zUploadAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/issues/{id}/attachments',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete an attachment
 */
export const deleteAttachment = <ThrowOnError extends boolean = false>(options: Options<DeleteAttachmentData, ThrowOnError>) => (options.client ?? client).delete<DeleteAttachmentResponses, DeleteAttachmentErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeleteAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/issues/{id}/attachments/{aid}',
    ...options
});

/**
 * Download an attachment
 */
export const downloadAttachment = <ThrowOnError extends boolean = false>(options: Options<DownloadAttachmentData, ThrowOnError>) => (options.client ?? client).get<DownloadAttachmentResponses, DownloadAttachmentErrors, ThrowOnError>({
    requestValidator: async (data) => await zDownloadAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/issues/{id}/attachments/{aid}',
    ...options
});

/**
 * Search users by name
 *
 * Returns matching users for autocomplete. Pass an empty query to list all users.
 */
export const searchUsers = <ThrowOnError extends boolean = false>(options?: Options<SearchUsersData, ThrowOnError>) => (options?.client ?? client).get<SearchUsersResponses, SearchUsersErrors, ThrowOnError>({
    requestValidator: async (data) => await zSearchUsersData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/search',
    ...options
});
