// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001' | (string & {});
};

export type Issue = {
    id: string;
    key: string;
    title: string;
    description: string;
    status: IssueStatus;
    priority: IssuePriority;
    assignee: string | null;
    createdBy: string;
    createdAt: string;
    updatedAt: string;
    attachments: Array<AttachmentMeta>;
    subtasks: Array<Subtask>;
    versions: IssueVersions;
};

export type IssueStatus = 'open' | 'in_progress' | 'closed';

export type IssuePriority = 'low' | 'medium' | 'high';

export type AttachmentMeta = {
    id: string;
    filename: string;
    mimetype: string;
    size: number;
    createdAt: string;
};

export type Subtask = {
    id: string;
    title: string;
    description: string;
    done: boolean;
};

export type IssueVersions = {
    affectedVersion: string;
    fixVersion: string;
};

export type IssueCreateInput = {
    title: string;
    description: string;
    priority?: IssuePriority;
    assignee?: string;
    subtasks: Array<SubtaskCreateInput>;
    versions: IssueVersionsInput;
};

export type SubtaskCreateInput = {
    title: string;
    description: string;
};

export type IssueVersionsInput = {
    affectedVersion?: string;
    fixVersion?: string;
};

export type IssueUpdateInput = {
    title?: string;
    description?: string;
    status?: IssueStatus;
    priority?: IssuePriority;
    assignee?: string;
    versions?: IssueVersionsInput;
};

export type Error = {
    error: string;
};

export type ValidationError = {
    error: string;
    details?: Array<{
        field: string;
        message: string;
    }>;
};

export type UnauthorizedError = {
    error: string;
};

export type NotFoundError = {
    error: string;
};

export type User = {
    id: string;
    name: string;
    email: string;
};

export type ListIssuesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/issues';
};

export type ListIssuesErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedError;
};

export type ListIssuesError = ListIssuesErrors[keyof ListIssuesErrors];

export type ListIssuesResponses = {
    /**
     * A list of issues
     */
    200: Array<Issue>;
};

export type ListIssuesResponse = ListIssuesResponses[keyof ListIssuesResponses];

export type CreateIssueData = {
    body?: IssueCreateInput;
    path?: never;
    query?: never;
    url: '/api/issues';
};

export type CreateIssueErrors = {
    /**
     * Validation error
     */
    400: ValidationError;
    /**
     * Unauthorized
     */
    401: UnauthorizedError;
};

export type CreateIssueError = CreateIssueErrors[keyof CreateIssueErrors];

export type CreateIssueResponses = {
    /**
     * The created issue
     */
    201: Issue;
};

export type CreateIssueResponse = CreateIssueResponses[keyof CreateIssueResponses];

export type DeleteIssueData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/issues/{id}';
};

export type DeleteIssueErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedError;
    /**
     * Issue not found
     */
    404: NotFoundError;
};

export type DeleteIssueError = DeleteIssueErrors[keyof DeleteIssueErrors];

export type DeleteIssueResponses = {
    /**
     * Issue deleted
     */
    204: void;
};

export type DeleteIssueResponse = DeleteIssueResponses[keyof DeleteIssueResponses];

export type GetIssueData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/issues/{id}';
};

export type GetIssueErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedError;
    /**
     * Issue not found
     */
    404: NotFoundError;
};

export type GetIssueError = GetIssueErrors[keyof GetIssueErrors];

export type GetIssueResponses = {
    /**
     * The issue
     */
    200: Issue;
};

export type GetIssueResponse = GetIssueResponses[keyof GetIssueResponses];

export type UpdateIssueData = {
    body?: IssueUpdateInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/issues/{id}';
};

export type UpdateIssueErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedError;
    /**
     * Issue not found
     */
    404: NotFoundError;
};

export type UpdateIssueError = UpdateIssueErrors[keyof UpdateIssueErrors];

export type UpdateIssueResponses = {
    /**
     * The updated issue
     */
    200: Issue;
};

export type UpdateIssueResponse = UpdateIssueResponses[keyof UpdateIssueResponses];

export type UploadAttachmentData = {
    body?: {
        file: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/issues/{id}/attachments';
};

export type UploadAttachmentErrors = {
    /**
     * No file uploaded
     */
    400: ValidationError;
    /**
     * Unauthorized
     */
    401: UnauthorizedError;
    /**
     * Issue not found
     */
    404: NotFoundError;
};

export type UploadAttachmentError = UploadAttachmentErrors[keyof UploadAttachmentErrors];

export type UploadAttachmentResponses = {
    /**
     * The created attachment metadata
     */
    201: AttachmentMeta;
};

export type UploadAttachmentResponse = UploadAttachmentResponses[keyof UploadAttachmentResponses];

export type DeleteAttachmentData = {
    body?: never;
    path: {
        id: string;
        aid: string;
    };
    query?: never;
    url: '/api/issues/{id}/attachments/{aid}';
};

export type DeleteAttachmentErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedError;
    /**
     * Attachment not found
     */
    404: NotFoundError;
};

export type DeleteAttachmentError = DeleteAttachmentErrors[keyof DeleteAttachmentErrors];

export type DeleteAttachmentResponses = {
    /**
     * Attachment deleted
     */
    204: void;
};

export type DeleteAttachmentResponse = DeleteAttachmentResponses[keyof DeleteAttachmentResponses];

export type DownloadAttachmentData = {
    body?: never;
    path: {
        id: string;
        aid: string;
    };
    query?: never;
    url: '/api/issues/{id}/attachments/{aid}';
};

export type DownloadAttachmentErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedError;
    /**
     * Attachment not found
     */
    404: NotFoundError;
};

export type DownloadAttachmentError = DownloadAttachmentErrors[keyof DownloadAttachmentErrors];

export type DownloadAttachmentResponses = {
    /**
     * The attachment file
     */
    200: Blob | File;
};

export type DownloadAttachmentResponse = DownloadAttachmentResponses[keyof DownloadAttachmentResponses];

export type SearchUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search query to match against user names
         */
        q?: string;
    };
    url: '/api/users/search';
};

export type SearchUsersErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedError;
};

export type SearchUsersError = SearchUsersErrors[keyof SearchUsersErrors];

export type SearchUsersResponses = {
    /**
     * A list of matching users
     */
    200: Array<User>;
};

export type SearchUsersResponse = SearchUsersResponses[keyof SearchUsersResponses];
