// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zIssueStatus = z.enum([
    'open',
    'in_progress',
    'closed'
]);

export const zIssuePriority = z.enum([
    'low',
    'medium',
    'high'
]);

export const zAttachmentMeta = z.object({
    id: z.uuid(),
    filename: z.string(),
    mimetype: z.string(),
    size: z.int(),
    createdAt: z.iso.datetime({ local: true })
});

export const zSubtask = z.object({
    id: z.uuid(),
    title: z.string(),
    description: z.string(),
    done: z.boolean()
});

export const zIssue = z.object({
    id: z.uuid(),
    key: z.string(),
    title: z.string(),
    description: z.string(),
    status: zIssueStatus,
    priority: zIssuePriority,
    assignee: z.string().nullable(),
    createdBy: z.string(),
    createdAt: z.iso.datetime({ local: true }),
    updatedAt: z.iso.datetime({ local: true }),
    attachments: z.array(zAttachmentMeta),
    subtasks: z.array(zSubtask)
});

export const zSubtaskCreateInput = z.object({
    title: z.string().min(1),
    description: z.string().min(1)
});

export const zIssueCreateInput = z.object({
    title: z.string().min(1),
    description: z.string().min(1),
    priority: zIssuePriority.optional(),
    assignee: z.string().optional(),
    subtasks: z.array(zSubtaskCreateInput).optional()
});

export const zIssueUpdateInput = z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    status: zIssueStatus.optional(),
    priority: zIssuePriority.optional(),
    assignee: z.string().optional()
});

export const zError = z.object({
    error: z.string()
});

export const zValidationError = z.object({
    error: z.string(),
    details: z.array(z.object({
        field: z.string(),
        message: z.string()
    })).optional()
});

export const zUnauthorizedError = z.object({
    error: z.string()
});

export const zNotFoundError = z.object({
    error: z.string()
});

export const zUser = z.object({
    id: z.string(),
    name: z.string(),
    email: z.email()
});

export const zListIssuesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * A list of issues
 */
export const zListIssuesResponse = z.array(zIssue);

export const zCreateIssueData = z.object({
    body: zIssueCreateInput.optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * The created issue
 */
export const zCreateIssueResponse = zIssue;

export const zDeleteIssueData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Issue deleted
 */
export const zDeleteIssueResponse = z.void();

export const zGetIssueData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * The issue
 */
export const zGetIssueResponse = zIssue;

export const zUpdateIssueData = z.object({
    body: zIssueUpdateInput.optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * The updated issue
 */
export const zUpdateIssueResponse = zIssue;

export const zUploadAttachmentData = z.object({
    body: z.object({
        file: z.string()
    }).optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * The created attachment metadata
 */
export const zUploadAttachmentResponse = zAttachmentMeta;

export const zDeleteAttachmentData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid(),
        aid: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Attachment deleted
 */
export const zDeleteAttachmentResponse = z.void();

export const zDownloadAttachmentData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid(),
        aid: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * The attachment file
 */
export const zDownloadAttachmentResponse = z.string();

export const zSearchUsersData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        q: z.string().optional()
    }).optional()
});

/**
 * A list of matching users
 */
export const zSearchUsersResponse = z.array(zUser);
