// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zIssueStatus = z.enum([
    'open',
    'in_progress',
    'closed'
]);

export const zIssuePriority = z.enum([
    'low',
    'medium',
    'high'
]);

export const zAttachmentMeta = z.object({
    id: z.uuid(),
    filename: z.string(),
    mimetype: z.string(),
    size: z.int(),
    createdAt: z.iso.datetime()
});

export const zSubtask = z.object({
    id: z.uuid(),
    title: z.string(),
    description: z.string(),
    done: z.boolean()
});

export const zIssueVersions = z.object({
    affectedVersion: z.string(),
    fixVersion: z.string()
});

export const zIssue = z.object({
    id: z.uuid(),
    key: z.string(),
    title: z.string(),
    description: z.string(),
    status: zIssueStatus,
    priority: zIssuePriority,
    assignee: z.string().nullable(),
    createdBy: z.string(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime(),
    attachments: z.array(zAttachmentMeta),
    subtasks: z.array(zSubtask),
    versions: zIssueVersions
});

export const zSubtaskCreateInput = z.object({
    title: z.string().min(1),
    description: z.string().min(1)
});

export const zIssueVersionsInput = z.object({
    affectedVersion: z.string().optional(),
    fixVersion: z.string().optional()
});

export const zIssueCreateInput = z.object({
    title: z.string().min(1),
    description: z.string().min(1),
    priority: zIssuePriority.optional(),
    assignee: z.string().optional(),
    subtasks: z.array(zSubtaskCreateInput),
    versions: zIssueVersionsInput
});

export const zIssueUpdateInput = z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    status: zIssueStatus.optional(),
    priority: zIssuePriority.optional(),
    assignee: z.string().optional(),
    versions: zIssueVersionsInput.optional()
});

export const zError = z.object({
    error: z.string()
});

export const zValidationError = z.object({
    error: z.string(),
    details: z.array(z.object({
        field: z.string(),
        message: z.string()
    })).optional()
});

export const zUnauthorizedError = z.object({
    error: z.string()
});

export const zNotFoundError = z.object({
    error: z.string()
});

export const zTitleValidationResponse = z.object({
    title: z.string(),
    available: z.boolean()
});

export const zUser = z.object({
    id: z.string(),
    name: z.string(),
    email: z.email()
});

export const zListIssuesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zCreateIssueData = z.object({
    body: zIssueCreateInput.optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zDeleteIssueData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zGetIssueData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zUpdateIssueData = z.object({
    body: zIssueUpdateInput.optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zValidateIssueTitleData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        title: z.string().min(1)
    })
});

export const zUploadAttachmentData = z.object({
    body: z.object({
        file: z.string()
    }).optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zDeleteAttachmentData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid(),
        aid: z.uuid()
    }),
    query: z.never().optional()
});

export const zDownloadAttachmentData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid(),
        aid: z.uuid()
    }),
    query: z.never().optional()
});

export const zSearchUsersData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        q: z.string().optional()
    }).optional()
});
